### ISSUE TITLE
Message size must be less than 20 chars

### ISSUE THREAD

**Issue by contateste123** [NaoNaoMe/USBTMC-Host-Driver#1]
Hi!

Is there a way to let the commands get past 20 bytes?

Some commands of my oscilloscope are very large, such as:

:MEASure:VRMS DISPlay,DC,CHANNEL1

And also even longer if I want to use a command that allows me to use annotations on screen.

Is there a way to send more than 20 bytes?

I really like your library it works quite well!
 
Thanks a lot!!!

**Comment by NaoNaoMe** [comment]
Thank you for your feedback.

The 20 bytes buffer was too short for some commands.
I increase the command length from 20 bytes to 64 bytes at [this commit.](https://github.com/NaoNaoMe/USBTMC-Host-Driver/commit/019ada004096fe4ff8a6b7487e5b69a3755f2746)
