### ISSUE TITLE
SAMD USB Host

### ISSUE THREAD

**Issue by AdamCummick** [NaoNaoMe/USBTMC-Host-Driver#2]
Would you be able to modify this library for the SAMD Arduino boards which have USB host built-in?

**Comment by NaoNaoMe** [comment]
It will work with the SAMD Arduino boards.

I suggest that you check out [USB_Host_Library_SAMD](https://github.com/gdsports/USB_Host_Library_SAMD).
USBTMC-Host-Driver is used by [USB_Host_Shield_2.0](https://github.com/felis/USB_Host_Shield_2.0), and USB_Host_Library_SAMD is based on USB_Host_Shield_2.0.

Unfortunately, I've never tried USB_Host_Library_SAMD, but it probably can work.
