### ISSUE TITLE
write OnReceived Callback to variable

### ISSUE THREAD

**Issue by itsyoshio** [NaoNaoMe/USBTMC-Host-Driver#3]
Hi there,

first of all, thanks for this awesome library.
I do have a question regarding the read from Device callback.
As i understand it now, each character received fires the callback, correct?

this, in turn, means that there's no way to see if a response string is complete / ended, yes?

How would read from the device and buffer / save the response in a String?

**Comment by NaoNaoMe** [comment]
Thank you for your interest in USBTMC-Host-Driver!

> As i understand it now, each character received fires the callback, correct?

Yes, you can receive data one by one on "OnReceived" callback.

> this, in turn, means that there's no way to see if a response string is complete / ended, yes?

Searching for a termination character is good for you.
In most case, all messages are terminated with a linefeed character.

> How would read from the device and buffer / save the response in a String?

The following code will be of help to you.
```
String receivedText;

void USBTMCAsync::OnReceived(uint8_t data)
{
  if (data != '\n') {
    receivedText += (char)data;
  }
  else{
    isReceived = true
  }
}
```

**Comment by itsyoshio** [comment]
Works like a charm, thank you so much.
