### ISSUE TITLE
Arduino as usbtmc standalone instrument

### ISSUE THREAD

**Issue by tuxgvf** [NaoNaoMe/USBTMC-Host-Driver#4]
Hi NaoNaoMe,
Any plans to develop an Arduino driver to bé directly reachable via usbtmc driver?
Is it technically possible? Do you know?
Thanks
Tux

**Comment by NaoNaoMe** [comment]
@tuxgvf 
Sorry , I'm late for reply.
What is the meaning of "directly reachable"?
For example, do you mean not using USB Host Shield?
Thanks

**Comment by tuxgvf** [comment]
I mean using the Arduino as an instrument. With a visa adress in USBxx:: instead of asrl::xx

**Comment by NaoNaoMe** [comment]
I don't have any plans about an arduino as instrument(USBTMC device), but it is technically possible.
